name: recipe_radar
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.0
  http: ^1.2.0
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/LoginBG.png
    - assets/images/Inventory.png
    - assets/images/google.png
    - assets/allrecipedata.json
    - assets/recipedetails2.json
    - assets/ingredients.json
    - assets/ingredient3.json

  uses-material-design: true
